apiVersion: v1
kind: Pod
metadata:
   name: lista-compras-mysql-pod
spec:
   containers:
      name:
         - name: container-mysql
           image: mysql
           ports:
              - containerPort: 3306
           env:
              - name: MYSQL_DATABASE
                value: "lista_compras_db"                
              - name: MYSQL_USER
                value: "root"
              - name: MYSQL_ALLOW_EMPTY_PASSWORD
                value: "1"
        
           
