apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
   name: statefulset-mysql
spec:
   serviceName: lista-compras-mysql
   template:
     metadata:
        labels:
         name: lista-compras-mysql-pod
     spec:
        containers:           
            - name: container-mysql
              image: mysql
              ports:
                - containerPort: 3306
              env:
                 - name: MYSQL_DATABASE
                   value: "lista_compras_db"                
                 - name: MYSQL_USER
                   value: "root"
                 - name: MYSQL_ALLOW_EMPTY_PASSWORD
                   value: "1"
              volumeMounts: 
                - name: volume-mysql
                  mountPath: /var/lib/mysql
        volumes:
           - name: volume-mysql
             persistentVolumeClaim:
                claimName: configuracao-mysql